In [1]:
import torch
import numpy as np
import sys

In [2]:
print("=" * 80)
print(" NumPy ↔ PyTorch Comprehensive Practice")
print("=" * 80)
print(f"NumPy version: {np.__version__}")
print(f"PyTorch version: {torch.__version__}")
print("=" * 80 + "\n")

 NumPy ↔ PyTorch Comprehensive Practice
NumPy version: 2.1.2
PyTorch version: 2.8.0+cu126



# ==========================================
# Section 1: Basic Conversions
# ==========================================

In [3]:
print("📌 Section 1: Basic Conversions")
print("-" * 50)

# NumPy to PyTorch
np_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
tensor_from_numpy = torch.from_numpy(np_array)

print("1.1 NumPy → PyTorch:")
print(f"    NumPy array:\n{np_array}")
print(f"    PyTorch tensor:\n{tensor_from_numpy}")
print(f"    Tensor dtype: {tensor_from_numpy.dtype}\n")

# PyTorch to NumPy
pytorch_tensor = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)
numpy_from_tensor = pytorch_tensor.numpy()

print("1.2 PyTorch → NumPy:")
print(f"    PyTorch tensor:\n{pytorch_tensor}")
print(f"    NumPy array:\n{numpy_from_tensor}")
print(f"    Array dtype: {numpy_from_tensor.dtype}\n")


📌 Section 1: Basic Conversions
--------------------------------------------------
1.1 NumPy → PyTorch:
    NumPy array:
[[1. 2. 3.]
 [4. 5. 6.]]
    PyTorch tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
    Tensor dtype: torch.float32

1.2 PyTorch → NumPy:
    PyTorch tensor:
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
    NumPy array:
[[ 7.  8.  9.]
 [10. 11. 12.]]
    Array dtype: float32



# ==========================================
# Section 2: Property Comparison
# ==========================================

In [4]:

# Create a random array for comparison
np_random = np.random.rand(3, 4).astype(np.float32)
torch_random = torch.from_numpy(np_random)

print("2.1 NumPy Array Properties:")
print(f"    Shape: {np_random.shape}")
print(f"    Dimensions: {np_random.ndim}")
print(f"    Total elements: {np_random.size}")
print(f"    Data type: {np_random.dtype}")
print(f"    Memory usage: {np_random.nbytes} bytes")
print(f"    Item size: {np_random.itemsize} bytes")
print(f"    Strides: {np_random.strides}")
print(f"    C-contiguous: {np_random.flags.c_contiguous}")
print(f"    Fortran-contiguous: {np_random.flags.f_contiguous}\n")

print("2.2 PyTorch Tensor Properties:")
print(f"    Shape: {torch_random.shape}")
print(f"    Size: {torch_random.size()}")
print(f"    Dimensions: {torch_random.ndim}")
print(f"    Total elements: {torch_random.numel()}")
print(f"    Data type: {torch_random.dtype}")
print(f"    Device: {torch_random.device}")
print(f"    Layout: {torch_random.layout}")
print(f"    Strides: {torch_random.stride()}")
print(f"    Requires grad: {torch_random.requires_grad}")
print(f"    Is contiguous: {torch_random.is_contiguous()}\n")

2.1 NumPy Array Properties:
    Shape: (3, 4)
    Dimensions: 2
    Total elements: 12
    Data type: float32
    Memory usage: 48 bytes
    Item size: 4 bytes
    Strides: (16, 4)
    C-contiguous: True
    Fortran-contiguous: False

2.2 PyTorch Tensor Properties:
    Shape: torch.Size([3, 4])
    Size: torch.Size([3, 4])
    Dimensions: 2
    Total elements: 12
    Data type: torch.float32
    Device: cpu
    Layout: torch.strided
    Strides: (4, 1)
    Requires grad: False
    Is contiguous: True



# ==========================================
# Section 3: Memory Sharing vs Copying
# ==========================================

In [ ]:
print("📌 Section 3: Memory Sharing vs Copying")
print("-" * 50)

# Shared memory (view)
print("3.1 Shared Memory (from_numpy creates a view):")
original_np = np.array([1.0, 2.0, 3.0, 4.0], dtype=np.float32)
tensor_shared = torch.from_numpy(original_np)
print(f"    Original NumPy: {original_np}")
print(f"    Tensor (shared): {tensor_shared}")

original_np[0] = 999.0
print(f"    After modifying NumPy[0] = 999:")
print(f"    NumPy: {original_np}")
print(f"    Tensor: {tensor_shared} ← Changed!\n")

# Independent copy
print("3.2 Independent Copy (tensor() creates a copy):")
original_np2 = np.array([1.0, 2.0, 3.0, 4.0], dtype=np.float32)
tensor_copy = torch.tensor(original_np2)
print(f"    Original NumPy: {original_np2}")
print(f"    Tensor (copy): {tensor_copy}")

original_np2[0] = 888.0
print(f"    After modifying NumPy[0] = 888:")
print(f"    NumPy: {original_np2}")
print(f"    Tensor: {tensor_copy} ← Unchanged!\n")

# ==========================================
# Section 4: Transpose and Contiguous Memory
# ==========================================

In [5]:
print("📌 Section 4: Transpose and Contiguous Memory")
print("-" * 50)

# NumPy transpose
print("4.1 NumPy Transpose:")
np_matrix = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
np_transposed = np_matrix.T

print(f"    Original shape: {np_matrix.shape}")
print(f"    Original:\n{np_matrix}")
print(f"    Original C-contiguous: {np_matrix.flags.c_contiguous}")
print(f"    Original strides: {np_matrix.strides}\n")

print(f"    Transposed shape: {np_transposed.shape}")
print(f"    Transposed:\n{np_transposed}")
print(f"    Transposed C-contiguous: {np_transposed.flags.c_contiguous}")
print(f"    Transposed strides: {np_transposed.strides}\n")


# PyTorch transpose
print("4.2 PyTorch Transpose:")
torch_matrix = torch.from_numpy(np_matrix)
torch_transposed = torch_matrix.t()

print(f"    Original shape: {torch_matrix.shape}")
print(f"    Original:\n{torch_matrix}")
print(f"    Original contiguous: {torch_matrix.is_contiguous()}")
print(f"    Original strides: {torch_matrix.stride()}\n")

print(f"    Transposed shape: {torch_transposed.shape}")
print(f"    Transposed:\n{torch_transposed}")
print(f"    Transposed contiguous: {torch_transposed.is_contiguous()} ← Not contiguous!")
print(f"    Transposed strides: {torch_transposed.stride()}\n")

# Making it contiguous again
print("4.3 Making Tensor Contiguous:")
torch_contiguous = torch_transposed.contiguous()
print(f"    After .contiguous(): {torch_contiguous.is_contiguous()}")
print(f"    New strides: {torch_contiguous.stride()}\n")

# NumPy transpose to PyTorch
print("4.4 NumPy Transposed → PyTorch:")
np_trans_to_torch = torch.from_numpy(np_transposed)
print(f"    NumPy transposed C-contiguous: {np_transposed.flags.c_contiguous}")
print(f"    Resulting tensor contiguous: {np_trans_to_torch.is_contiguous()}")
print(f"    Tensor strides: {np_trans_to_torch.stride()}\n")

📌 Section 4: Transpose and Contiguous Memory
--------------------------------------------------
4.1 NumPy Transpose:
    Original shape: (2, 3)
    Original:
[[1. 2. 3.]
 [4. 5. 6.]]
    Original C-contiguous: True
    Original strides: (12, 4)

    Transposed shape: (3, 2)
    Transposed:
[[1. 4.]
 [2. 5.]
 [3. 6.]]
    Transposed C-contiguous: False
    Transposed strides: (4, 12)

4.2 PyTorch Transpose:
    Original shape: torch.Size([2, 3])
    Original:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
    Original contiguous: True
    Original strides: (3, 1)

    Transposed shape: torch.Size([3, 2])
    Transposed:
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
    Transposed contiguous: False ← Not contiguous!
    Transposed strides: (1, 3)

4.3 Making Tensor Contiguous:
    After .contiguous(): True
    New strides: (2, 1)

4.4 NumPy Transposed → PyTorch:
    NumPy transposed C-contiguous: False
    Resulting tensor contiguous: False
    Tensor strides: (1, 3)



# ==========================================
# Section 5: Practical Applications
# ==========================================

In [7]:
print("📌 Section 5: Practical Applications")
print("-" * 50)

# Using NumPy functions with PyTorch tensors
print("5.1 NumPy Functions on PyTorch Tensors:")
tensor = torch.tensor([1.0, 4.0, 9.0, 16.0])
print(f"    Original tensor: {tensor}")

# Convert to NumPy, apply function, convert back
np_temp = tensor.numpy()
np_result = np.sqrt(np_temp)
result_tensor = torch.from_numpy(np_result)
print(f"    After np.sqrt: {result_tensor}\n")

# Complex operation chain
print("5.2 Operation Chain (PyTorch → NumPy → PyTorch):")
torch_data = torch.randn(2, 3)
print(f"    Random tensor:\n{torch_data}")

# Chain of operations
np_data = torch_data.numpy()
np_processed = np.exp(np_data) / np.sum(np.exp(np_data))  # Softmax
torch_result = torch.from_numpy(np_processed)
print(f"    After softmax (via NumPy):\n{torch_result}")
print(f"    Sum (should be ~1.0): {torch_result.sum():.6f}\n")

📌 Section 5: Practical Applications
--------------------------------------------------
5.1 NumPy Functions on PyTorch Tensors:
    Original tensor: tensor([ 1.,  4.,  9., 16.])
    After np.sqrt: tensor([1., 2., 3., 4.])

5.2 Operation Chain (PyTorch → NumPy → PyTorch):
    Random tensor:
tensor([[ 0.8057, -0.6177, -0.2382],
        [-2.9586, -1.4592, -1.5954]])
    After softmax (via NumPy):
tensor([[0.5523, 0.1330, 0.1945],
        [0.0128, 0.0573, 0.0500]])
    Sum (should be ~1.0): 1.000000



In [ ]:
# ==========================================
# Section 6: Memory Layout Visualization
# ==========================================

In [6]:
print("📌 Section 6: Memory Layout Visualization")
print("-" * 50)

def print_memory_info(name, arr_or_tensor):
    """Helper function to print memory layout information"""
    if isinstance(arr_or_tensor, np.ndarray):
        print(f"{name}:")
        print(f"    Shape: {arr_or_tensor.shape}")
        print(f"    Strides: {arr_or_tensor.strides}")
        print(f"    C-contiguous: {arr_or_tensor.flags.c_contiguous}")
        print(f"    F-contiguous: {arr_or_tensor.flags.f_contiguous}")
    else:  # PyTorch tensor
        print(f"{name}:")
        print(f"    Shape: {arr_or_tensor.shape}")
        print(f"    Strides: {arr_or_tensor.stride()}")
        print(f"    Contiguous: {arr_or_tensor.is_contiguous()}")

# Create a 3D example to better show memory layout
print("6.1 3D Array/Tensor Memory Layout:")
np_3d = np.arange(24).reshape(2, 3, 4).astype(np.float32)
torch_3d = torch.from_numpy(np_3d)

print_memory_info("NumPy 3D", np_3d)
print_memory_info("PyTorch 3D", torch_3d)
print()

# Permute dimensions
np_permuted = np_3d.transpose(2, 0, 1)
torch_permuted = torch_3d.permute(2, 0, 1)

print("6.2 After Permutation (2, 0, 1):")
print_memory_info("NumPy permuted", np_permuted)
print_memory_info("PyTorch permuted", torch_permuted)
print()

# Show the effect of contiguous
torch_cont = torch_permuted.contiguous()
print("6.3 After making PyTorch tensor contiguous:")
print_memory_info("PyTorch contiguous", torch_cont)

print("\n" + "=" * 80)
print(" Practice Complete!")
print("=" * 80)

📌 Section 6: Memory Layout Visualization
--------------------------------------------------
6.1 3D Array/Tensor Memory Layout:
NumPy 3D:
    Shape: (2, 3, 4)
    Strides: (48, 16, 4)
    C-contiguous: True
    F-contiguous: False
PyTorch 3D:
    Shape: torch.Size([2, 3, 4])
    Strides: (12, 4, 1)
    Contiguous: True

6.2 After Permutation (2, 0, 1):
NumPy permuted:
    Shape: (4, 2, 3)
    Strides: (4, 48, 16)
    C-contiguous: False
    F-contiguous: False
PyTorch permuted:
    Shape: torch.Size([4, 2, 3])
    Strides: (1, 12, 4)
    Contiguous: False

6.3 After making PyTorch tensor contiguous:
PyTorch contiguous:
    Shape: torch.Size([4, 2, 3])
    Strides: (6, 3, 1)
    Contiguous: True

 Practice Complete!
